show_print: True

# model options
use_rocket: False
num_neurons: 10
num_layers: 4

# dataset global options
dataset_name: ElectricDevices # ChlorineConcentration # NonInvasiveFetalECGThorax2
train_size: 0.8
dataloader_num_workers: 8

# optimizer options
batch_size: 512
batch_size_testing: 4096
learning_rate: 0.001
max_epochs: 1000
patience_lr: 200000
patience: 100000
use_cocob: False #True

