show_print: True

saving_path: ../../jax_results

# model options
use_rocket: True
num_neurons: 17
num_layers: 10

# dataset global options
dataset_name: FaceAll #MelbournePedestrian # ChlorineConcentration # NonInvasiveFetalECGThorax2
train_size: 0.8
dataloader_num_workers: 1

# optimizer options
batch_size: 128
batch_size_testing: 4096
learning_rate: 0.001
max_epochs: 1000
patience_lr: 200000
patience: 100000
use_cocob: False #True
quantize_adam: True
use_dynamictree_quantization: True

sample_dataset_iid: True

