show_print: True

# dataset global options
dataset_name: ChlorineConcentration
train_size: 0.8
dataloader_num_workers: 8

# optimizer options
batch_size: 512
batch_size_testing: 4096
learning_rate: 0.01
max_epochs: 1000
patience_lr: 5000
patience: 100000
use_cocob: True #True

